### ISSUE TITLE
Question of Rank@k and Top@k

### ISSUE THREAD

**Issue by cxxpython9** [bnu-wangxun/Deep_Metric#42]
I have scanned the code of evalutions and now am confused of the metric 'rank@k'.
Is it the same with metric 'top@k'?

I revised the script 'test.py' and add additional functions to get the metric 'top@k'. 
As you know, the two metrics are obtained from the matrix 'sim_mat' which is provided by you.
But the results of them are not equal sometimes. 

So, could you explain the concept of 'recall@k' in the view of your code?

Thank you very much.

**Comment by bnu-wangxun** [comment]
please refer to the paper:
https://arxiv.org/pdf/1511.06452.pdf
